### PR TITLE
Rebase openwrt/openwrt master onto lucize/openwrt rk3328

### PR DESCRIPTION
**Pull request by CanadianBaconBoi**
Hiya!

I've rebased your branch `rk3328` onto the upstream master branch to hopefully get these changes you have made pushed onto upstream.

Please review this and let me know if you have any question.

Kudos!
- CanadianBacon

### CODE REVIEW

**Comment by lucize** [comment]
this is a bad pull request, you merged everything

**Comment by CanadianBaconBoi** [comment]
Sorry, I'm still new to git.

**Comment by lucize** [comment]
You have to branch from current master and add only the new changes, one by one, you can use remote pr, but I guess I'll update the original one, I was with the assumption that it will be rebased by hand

**Comment by CanadianBaconBoi** [comment]
Alright, I'll do that soon :)

**Pull request closed without merging**
